#!/bin/sh
set -e
# 备份用户原有配置
if [ -f "${IPKG_INSTROOT}/etc/config/nutstore_backup" ]; then
	cp -f "${IPKG_INSTROOT}/etc/config/nutstore_backup" "/tmp/luci-app-nutstore-backup_config_backup.tar.gz"
fi
# 启用并启动守护进程
if [ -z "${IPKG_INSTROOT}" ]; then
	/etc/init.d/nutstore-optimize-guard enable
	/etc/init.d/nutstore-optimize-guard restart 2>/dev/null
	rm -rf /tmp/luci-indexcache /tmp/luci-modulecache
fi
exit 0
