#!/bin/sh /etc/rc.common
START=99
STOP=10

USE_PROCD=1

start_service() {
    procd_open_instance
    procd_set_param command /bin/true
    procd_set_param respawn 0 0 0
    procd_close_instance

    logger -t "jianguoyun" "坚果云备份服务启动成功"
}

stop_service() {
    logger -t "jianguoyun" "坚果云备份服务已停止"
}

restart() {
    stop
    start
}
