#!/bin/sh /etc/rc.common
START=99
USE_PROCD=1

start_service() {
    procd_open_instance
    procd_set_param command /bin/sh -c "while true; do /usr/bin/nutstore-adblock.sh guard; /usr/bin/nutstore-parent.sh guard; sleep 60; done"
    procd_set_param respawn
    procd_close_instance
}

stop_service() {
    killall -9 nutstore-adblock.sh nutstore-parent.sh 2>/dev/null
}

enable() {
    default_enabled=$(uci get nutstore_backup.global.guard_enable 2>/dev/null)
    [ "$default_enabled" != "0" ] && ln -s /etc/init.d/nutstore-optimize-guard /etc/rc.d/S99_nutstore-optimize-guard 2>/dev/null
}

disable() {
    rm -f /etc/rc.d/S99_nutstore-optimize-guard 2>/dev/null
}
